"""add_notification_fields

Revision ID: 1c310a9f5289
Revises: 2fe782a2d833
Create Date: 2026-06-22 15:36:42.950120
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c310a9f5289'
down_revision: Union[str, None] = '2fe782a2d833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('notified_24h', sa.Boolean(), nullable=False))
    op.add_column('bookings', sa.Column('notified_2h', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'notified_2h')
    op.drop_column('bookings', 'notified_24h')
    # ### end Alembic commands ###
