"""add_user_bonus_promo

Revision ID: 2fe782a2d833
Revises: f412a206a21e
Create Date: 2026-06-22 15:31:47.451927
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe782a2d833'
down_revision: Union[str, None] = 'f412a206a21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bonus_points', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('promo_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'promo_code')
    op.drop_column('users', 'bonus_points')
    # ### end Alembic commands ###
