"""add_master_schedules

Revision ID: f412a206a21e
Revises: 78fc1fef322a
Create Date: 2026-06-22 15:24:28.795584
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f412a206a21e'
down_revision: Union[str, None] = '78fc1fef322a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_schedules',
    sa.Column('master_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='0=Monday, 6=Sunday'),
    sa.Column('start_time', sa.String(length=5), nullable=False, comment='HH:MM'),
    sa.Column('end_time', sa.String(length=5), nullable=False, comment='HH:MM'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_schedules')
    # ### end Alembic commands ###
